In [ ]:
import pandas as pd
df = pd.read_csv("data\hospital_readmissions.csv")
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [ ]:
diag_cols = ["diag_1", "diag_2", "diag_3"]
categories = pd.unique(df[diag_cols].values.ravel())
one_hot = pd.DataFrame(0, index=df.index, columns=categories)
for col in diag_cols:
    one_hot = one_hot | pd.get_dummies(df[col]).reindex(columns=categories, fill_value=0)
df_dropped = df.drop(columns=diag_cols)
insert_at = 9
left = df_dropped.iloc[:, :insert_at]
right = df_dropped.iloc[:, insert_at:]
df_final = pd.concat([left, one_hot, right], axis=1)
print(df_final.head())

       age  time_in_hospital  n_lab_procedures  n_procedures  n_medications  \
0  [70-80)                 8                72             1             18
1  [70-80)                 3                34             2             13
2  [50-60)                 5                45             0             18
3  [70-80)                 2                36             0             12
4  [60-70)                 1                42             0              7

   n_outpatient  n_inpatient  n_emergency medical_specialty  Circulatory  ...  \
0             2            0            0           Missing         True  ...
1             0            0            0             Other        False  ...
2             0            0            0           Missing         True  ...
3             1            0            0           Missing         True  ...
4             0            0            0  InternalMedicine         True  ...

   Diabetes  Injury  Digestive  Musculoskeletal  Missing  glucose_test  \
0     False   False      False            False    False            no
1     False   False      False            False    False            no
2     False   False      False            False    False            no
3      True   False      False            False    False            no
4     False   False      False            False    False            no

   A1Ctest change diabetes_med readmitted
0       no     no          yes         no
1       no     no          yes         no
2       no    yes          yes        yes
3       no    yes          yes        yes
4       no     no          yes         no

[5 rows x 22 columns]